DROP SEQUENCE CURRENCY_ID_GENERATOR
/
DROP PROCEDURE SAVE_CURRENCY
/
DROP PROCEDURE LOAD_CURRENCY
/
DROP PROCEDURE UPDATE_CURRENCY
/
DROP FUNCTION COUNT_CURRENCY
/
DROP PROCEDURE REMOVE_CURRENCY
/
DROP FUNCTION LOAD_ALL_CURRENCY
/
DROP TYPE CURRENCY_ARRAY
/
DROP TYPE CURRENCY_TYPE FORCE
/
DROP PROCEDURE CLEAR_CURRENCY
/
DROP TABLE CURRENCY
/