DROP TABLE FOUND
/
DROP SEQUENCE FOUND_ID_GENERATOR
/
DROP PROCEDURE SAVE_FOUND
/
DROP PROCEDURE LOAD_FOUND
/
DROP PROCEDURE UPDATE_FOUND
/
DROP FUNCTION COUNT_FOUND
/
DROP PROCEDURE REMOVE_FOUND
/
DROP FUNCTION LOAD_ALL_FOUND
/
DROP TYPE FOUND_ARRAY
/
DROP TYPE FOUND_TYPE FORCE
/
DROP PROCEDURE CLEAR_FOUND
/