DROP TABLE DEPARTMENT
/
DROP SEQUENCE DEPARTMENT_ID_GENERATOR
/
DROP PROCEDURE SAVE_DEPARTMENT
/
DROP PROCEDURE LOAD_DEPARTMENT
/
DROP PROCEDURE UPDATE_DEPARTMENT
/
DROP FUNCTION COUNT_DEPARTMENT
/
DROP PROCEDURE REMOVE_DEPARTMENT
/
DROP FUNCTION LOAD_ALL_DEPARTMENT
/
DROP TYPE DEPARTMENT_ARRAY
/
DROP TYPE DEPARTMENT_TYPE FORCE
/
DROP PROCEDURE CLEAR_DEPARTMENT
/