DROP TABLE BANKER
/
DROP SEQUENCE BANKER_ID_GENERATOR
/
DROP PROCEDURE SAVE_BANKER
/
DROP PROCEDURE LOAD_BANKER
/
DROP PROCEDURE UPDATE_BANKER
/
DROP FUNCTION COUNT_BANKER
/
DROP PROCEDURE REMOVE_BANKER
/
DROP FUNCTION LOAD_ALL_BANKER
/
DROP TYPE BANKER_ARRAY
/
DROP TYPE BANKER_TYPE FORCE
/