DROP TABLE CLIENT
/
DROP SEQUENCE CLIENT_ID_GENERATOR
/
DROP PROCEDURE SAVE_CLIENT
/
DROP PROCEDURE LOAD_CLIENT
/
DROP PROCEDURE UPDATE_CLIENT
/
DROP FUNCTION COUNT_CLIENT
/
DROP PROCEDURE REMOVE_CLIENT
/
DROP FUNCTION LOAD_ALL_CLIENT
/
DROP TYPE CLIENT_ARRAY
/
DROP TYPE CLIENT_TYPE FORCE
/