DROP TABLE DEPOSIT
/
DROP SEQUENCE DEPOSIT_ID_GENERATOR
/
DROP PROCEDURE SAVE_DEPOSIT
/
DROP PROCEDURE LOAD_DEPOSIT
/
DROP PROCEDURE UPDATE_DEPOSIT
/
DROP FUNCTION COUNT_DEPOSIT
/
DROP PROCEDURE REMOVE_DEPOSIT
/
DROP FUNCTION LOAD_ALL_DEPOSIT
/
DROP TYPE DEPOSIT_ARRAY
/
DROP TYPE DEPOSIT_TYPE FORCE
/
DROP PROCEDURE CLEAR_DEPOSIT
/