DROP SEQUENCE BILLCARD_ID_GENERATOR
/
DROP PROCEDURE SAVE_BILLCARD
/
DROP PROCEDURE LOAD_BILLCARD
/
DROP PROCEDURE UPDATE_BILLCARD
/
DROP FUNCTION COUNT_BILLCARD
/
DROP PROCEDURE REMOVE_BILLCARD
/
DROP FUNCTION LOAD_ALL_BILLCARD
/
DROP TYPE BILLCARD_ARRAY
/
DROP TYPE BILLCARD_TYPE FORCE
/
DROP PROCEDURE CLEAR_BILLCARD
/
DROP TABLE BILLCARD
/