DROP TABLE CREDIT
/
DROP SEQUENCE CREDIT_ID_GENERATOR
/
DROP PROCEDURE SAVE_CREDIT
/
DROP PROCEDURE LOAD_CREDIT
/
DROP PROCEDURE UPDATE_CREDIT
/
DROP FUNCTION COUNT_CREDIT
/
DROP PROCEDURE REMOVE_CREDIT
/
DROP FUNCTION LOAD_ALL_CREDIT
/
DROP TYPE CREDIT_ARRAY
/
DROP TYPE CREDIT_TYPE FORCE
/
DROP PROCEDURE CLEAR_CREDIT
/