DROP TABLE CREDITCARD
/
DROP SEQUENCE CREDITCARD_ID_GENERATOR
/
DROP PROCEDURE CREDITCARD_BILLCARD
/
DROP PROCEDURE CREDITCARD_BILLCARD
/
DROP PROCEDURE CREDITCARD_BILLCARD
/
DROP FUNCTION CREDITCARD_BILLCARD
/
DROP PROCEDURE REMOVE_CREDITCARD
/
DROP FUNCTION LOAD_ALL_CREDITCARD
/
DROP TYPE CREDITCARD_ARRAY
/
DROP TYPE CREDITCARD_TYPE FORCE
/
DROP PROCEDURE CLEAR_CREDITCARD
/