DROP SEQUENCE CREDITCARD_ID_GENERATOR
/
DROP PROCEDURE SAVE_CREDITCARD
/
DROP PROCEDURE LOAD_CREDITCARD
/
DROP PROCEDURE UPDATE_CREDITCARD
/
DROP FUNCTION COUNT_CREDITCARD
/
DROP PROCEDURE REMOVE_CREDITCARD
/
DROP FUNCTION LOAD_ALL_CREDITCARD
/
DROP TYPE CREDITCARD_ARRAY
/
DROP TYPE CREDITCARD_TYPE FORCE
/
DROP PROCEDURE CLEAR_CREDITCARD
/
DROP TABLE CREDITCARD
/